import { SIHLogo } from './components/icons/SIHLogo';
import { TranslationKey, Speaker, Country, Language, Partner } from './types';

export const LANGUAGES: Language[] = ['ru', 'kz', 'en'];

export const translations = {
    ru: {
        nav_about: 'О событии',
        nav_program: 'Программа',
        nav_competition: 'Конкурс',
        nav_exhibition: 'Выставка',
        nav_speakers: 'Спикеры',
        nav_registration: 'Регистрация',
        main_title: 'Международный Курултай социальных предпринимателей 2025',
        main_subtitle: 'Объединяем лидеров, инноваторов и меценатов для решения социальных вызовов.',
        main_date: 'ноября 2025',
        main_countries: 'стран-участников',
        main_participants: 'участников',
        program_title: 'Программа мероприятия',
        program_link: 'СМОТРЕТЬ ПРОГРАММУ ↗️',
        competition_title: 'Ежегодная премия «Лучший социальный предприниматель 2025»',
        competition_desc_title: 'Описание конкурса',
        competition_desc_text: 'Ключевое событие курултая для выявления и поощрения лучших социальных проектов.',
        competition_link: 'ПОДРОБНЕЕ ↗️',
        tech_task_title: 'Техническое задание',
        tech_task_desc: 'Ознакомьтесь с критериями для создания видеоролика о вашем проекте для участия в конкурсе.',
        video_criteria_link: 'КРИТЕРИИ ДЛЯ ВИДЕО ↗️',
        exhibition_title: 'Ярмарка и Фотовыставка',
        exhibition_subtitle: 'Ярмарка продукции социальных предпринимателей и фотовыставка «Социальные предприниматели в лицах».',
        exhibition_text: 'Хотите представить свою продукцию? Зарегистрируйтесь для участия в ярмарке.',
        exhibition_link: 'Регистрация на участие',
        speakers_title: 'Спикеры',
        speaker1_title: 'Министр науки и высшего образования РК',
        speaker2_title: 'Министр труда и социальной защиты населения РК',
        speaker3_title: 'Аким города Астаны',
        speaker4_title: 'Основатель Social Innovation Hub',
        speaker5_title: 'Общественный деятель, директор ОФ «Милосердие»',
        speaker6_title: 'Двукратный олимпийский чемпион',
        speaker7_title: 'Популярный имам',
        speaker8_title: 'Семикратный рекордсмен книги рекордов Гиннеса',
        speaker9_title: 'Основатель Astana HUB',
        speaker10_title: 'Основатель проекта «JANAMEN»',
        registration_title: 'Регистрация на участие',
        form_name: 'ФИО (полностью)',
        form_region: 'Регион',
        form_phone: 'Контактный телефон',
        form_iin: 'ИИН (для проверки службы госохраны)',
        form_submit: 'Зарегистрироваться',
        success_message: 'Вы успешно зарегистрированы!',
        contacts_title: 'Контакты',
    },
    kz: {
        nav_about: 'Іс-шара туралы',
        nav_program: 'Бағдарлама',
        nav_competition: 'Байқау',
        nav_exhibition: 'Көрме',
        nav_speakers: 'Спикерлер',
        nav_registration: 'Тіркелу',
        main_title: 'Әлеуметтік кәсіпкерлердің халықаралық құрылтайы 2025',
        main_subtitle: 'Әлеуметтік мәселелерді шешу үшін көшбасшыларды, инноваторларды және меценаттарды біріктіреміз.',
        main_date: 'қараша 2025',
        main_countries: 'қатысушы ел',
        main_participants: 'қатысушы',
        program_title: 'Іс-шара бағдарламасы',
        program_link: 'БАҒДАРЛАМАНЫ КӨРУ ↗️',
        competition_title: '"Үздік әлеуметтік кәсіпкер 2025" жыл сайынғы сыйлығы',
        competition_desc_title: 'Байқау сипаттамасы',
        competition_desc_text: 'Үздік әлеуметтік жобаларды анықтау және марапаттауға арналған құрылтайдың негізгі оқиғасы.',
        competition_link: 'ТОЛЫҒЫРАҚ ↗️',
        tech_task_title: 'Техникалық тапсырма',
        tech_task_desc: 'Байқауға қатысу үшін жобаңыз туралы бейнеролик жасау критерийлерімен танысыңыз.',
        video_criteria_link: 'БЕЙНЕРОЛИК КРИТЕРИЙЛЕРІ ↗️',
        exhibition_title: 'Жәрмеңке және Фотокөрме',
        exhibition_subtitle: 'Әлеуметтік кәсіпкерлер өнімдерінің жәрмеңкесі және «Әлеуметтік кәсіпкерлер келбеті» фотокөрмесі.',
        exhibition_text: 'Өз өніміңізді ұсынғыңыз келе ме? Жәрмеңкеге қатысу үшін тіркеліңіз.',
        exhibition_link: 'Қатысуға тіркелу',
        speakers_title: 'Спикерлер',
        speaker1_title: 'ҚР Ғылым және жоғары білім министрі',
        speaker2_title: 'ҚР Еңбек және халықты әлеуметтік қорғау министрі',
        speaker3_title: 'Астана қаласының әкімі',
        speaker4_title: 'Social Innovation Hub негізін қалаушы',
        speaker5_title: 'Қоғам қайраткері, «Милосердие» ҚҚ директоры',
        speaker6_title: 'Екі дүркін Олимпиада чемпионы',
        speaker7_title: 'Танымал имам',
        speaker8_title: 'Гиннестің рекордтар кітабының жеті дүркін рекордшысы',
        speaker9_title: 'Astana HUB негізін қалаушы',
        speaker10_title: '«JANAMEN» жобасының негізін қалаушы',
        registration_title: 'Қатысуға тіркелу',
        form_name: 'Аты-жөні (толық)',
        form_region: 'Аймақ',
        form_phone: 'Байланыс телефоны',
        form_iin: 'ЖСН (мемлекеттік күзет тексеруі үшін)',
        form_submit: 'Тіркелу',
        success_message: 'Сіз сәтті тіркелдіңіз!',
        contacts_title: 'Байланыстар',
    },
    en: {
        nav_about: 'About',
        nav_program: 'Program',
        nav_competition: 'Competition',
        nav_exhibition: 'Exhibition',
        nav_speakers: 'Speakers',
        nav_registration: 'Registration',
        main_title: 'International Kurultai of Social Entrepreneurs 2025',
        main_subtitle: 'Uniting leaders, innovators, and patrons to solve social challenges.',
        main_date: 'November 2025',
        main_countries: 'participating countries',
        main_participants: 'participants',
        program_title: 'Event Program',
        program_link: 'VIEW PROGRAM ↗️',
        competition_title: 'Annual "Best Social Entrepreneur 2025" Award',
        competition_desc_title: 'Competition Details',
        competition_desc_text: 'A key event of the Kurultai to identify and reward the best social projects.',
        competition_link: 'LEARN MORE ↗️',
        tech_task_title: 'Technical Task',
        tech_task_desc: 'Review the criteria for creating a video about your project to participate in the competition.',
        video_criteria_link: 'VIDEO CRITERIA ↗️',
        exhibition_title: 'Fair & Photo Exhibition',
        exhibition_subtitle: "A fair for social entrepreneurs' products and a photo exhibition 'Faces of Social Entrepreneurs'.",
        exhibition_text: 'Want to showcase your products? Register to participate in the fair.',
        exhibition_link: 'Register for participation',
        speakers_title: 'Speakers',
        speaker1_title: 'Minister of Science and Higher Education, RK',
        speaker2_title: 'Minister of Labour and Social Protection, RK',
        speaker3_title: 'Akim of Astana city',
        speaker4_title: 'Founder of Social Innovation Hub',
        speaker5_title: 'Public figure, Director of "Mercy" Foundation',
        speaker6_title: 'Two-time Olympic champion',
        speaker7_title: 'Popular Imam',
        speaker8_title: 'Seven-time Guinness World Record holder',
        speaker9_title: 'Founder of Astana HUB',
        speaker10_title: 'Founder of "JANAMEN" project',
        registration_title: 'Registration for Participation',
        form_name: 'Full Name',
        form_region: 'Region',
        form_phone: 'Contact Phone',
        form_iin: 'IIN (for state security check)',
        form_submit: 'Register',
        success_message: 'You have been successfully registered!',
        contacts_title: 'Contacts',
    }
};

export const LINKS = {
    program: {
        ru: 'https://docs.google.com/document/d/1_placeholder_ru/edit?usp=sharing',
        kz: 'https://docs.google.com/document/d/1_placeholder_kz/edit?usp=sharing',
        en: 'https://docs.google.com/document/d/1_placeholder_en/edit?usp=sharing',
    },
    competition: {
        ru: 'https://docs.google.com/document/d/2_placeholder_ru/edit?usp=sharing',
        kz: 'https://docs.google.com/document/d/2_placeholder_kz/edit?usp=sharing',
        en: 'https://docs.google.com/document/d/2_placeholder_en/edit?usp=sharing',
    },
    video_criteria: {
        ru: 'https://docs.google.com/document/d/3_placeholder_ru/edit?usp=sharing',
        kz: 'https://docs.google.com/document/d/3_placeholder_kz/edit?usp=sharing',
        en: 'https://docs.google.com/document/d/3_placeholder_en/edit?usp=sharing',
    },
    main_registration: 'https://docs.google.com/forms/d/e/1FAIpQLSc-placeholder-main/viewform?usp=sf_link',
    fair_registration: 'https://docs.google.com/forms/d/e/1FAIpQLSc-placeholder-fair/viewform?usp=sf_link',
};

export const SPEAKERS: Speaker[] = [
    { name: 'Саясат Нурбек', titleKey: 'speaker1_title', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTGnc6UFiPtP1spNYhETQ-g5eyzCpcqxZTVw&s' },
    { name: 'Светлана Жакупова', titleKey: 'speaker2_title', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYzpQtuIMLYipnbSrVXhxOD7cAWIMaRml7rw&s' },
    { name: 'Женис Касымбек', titleKey: 'speaker3_title', imageUrl: 'https://www.gov.kz/uploads/2022/12/8/bdfcfff0425d31392bdad92922f3175a_original.56122.jpeg' },
    { name: 'Эмин Аскеров', titleKey: 'speaker4_title', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUsyg090NMPz1btYjZ0_hDEqHewbLUwjNW9A&s' },
    { name: 'Аружан Саин', titleKey: 'speaker5_title', imageUrl: 'https://aruzhansain.kz/wp-content/uploads/2023/08/aruzhan.jpg' },
    { name: 'Илья Ильин', titleKey: 'speaker6_title', imageUrl: 'https://massaget.kz/userdata/news/news_4515/photo.jpg' },
    { name: 'Нурлан кажы Асанов', titleKey: 'speaker7_title', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNo9qm0aom1ZvkKAzW1RPvVA3GrJBp_ugAEg&s' },
    { name: 'Сергей Цирюльников', titleKey: 'speaker8_title', imageUrl: 'https://offside.kz/cache/imagine/1200/uploads/news/2025/05/28/6837613b5f1e5677726632.jpg' },
    { name: 'Магжан Мадиев', titleKey: 'speaker9_title', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmBZC8xErY0lVaLzFkCxuqPw9zFH9hulJPwA&s' },
    { name: 'Айтым Жакупов', titleKey: 'speaker10_title', imageUrl: 'https://churchill.kz/wp-content/uploads/2025/08/ad_4nxcpq9dlmckcczhhuvppaohwzu0jzcvmrmuivrz4vyamk7zx2ibgzl4hwlhl7qntv-z3tx9ox_ikoxvsruuvqoqh2ma-aq_qjitc1vja_xjzyiw3dc3fxusz4kw5axfprs-cojbt-870x600.jpg' },
];

export const COUNTRIES: Country[] = [
    { name: "Азербайджан", code: "AZ", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/2560px-Flag_of_Azerbaijan.svg.png" },
    { name: "Грузия", code: "GE", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/2560px-Flag_of_Georgia.svg.png" },
    { name: "Индия", code: "IN", flagUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/2560px-Flag_of_India.svg.png" },
    { name: "Израиль", code: "IL", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/2560px-Flag_of_Israel.svg.png" },
    { name: "Кыргызстан", code: "KG", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/2560px-Flag_of_Kyrgyzstan.svg.png" },
    { name: "Россия", code: "RU", flagUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/2560px-Flag_of_Russia.svg.png" },
    { name: "Южная Корея", code: "KR", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/2560px-Flag_of_South_Korea.svg.png" },
    { name: "Таджикистан", code: "TJ", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/2560px-Flag_of_Tajikistan.svg.png" },
    { name: "США", code: "US", flagUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/2560px-Flag_of_the_United_States.svg.png" },
    { name: "Узбекистан", code: "UZ", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/2560px-Flag_of_Uzbekistan.svg.png" },
];

// FIX: Update PARTNERS array to use the Partner type and include component-based partners.
// This allows TypeScript to correctly infer types in PartnersSection.tsx and fixes the error.
export const PARTNERS: Partner[] = [
    { type: 'image', value: 'https://optim.tildacdn.ink/tild3762-3632-4433-a635-356239356136/-/format/webp/13logo.png.webp' },
    { type: 'image', value: 'https://optim.tildacdn.ink/tild3963-3831-4838-a632-363762663263/-/resize/450x/-/format/webp/images.png.webp' },
    { type: 'image', value: 'https://optim.tildacdn.ink/tild3534-6235-4865-b939-363461643639/-/resize/400x/-/format/webp/612e8519-e883-4eb4-b.png.webp' },
];